is_train: True
out_path: ./outputs/audio2pose_upper_batch_1_loss_left_arm/ 

##-----------For run in lab server-----------##
# root_path: /data/nas07/PersonalData/danh/PantoMatrix/beat_partial/30_ones
# train_data_path: /beat_4english_30_30/train_norm/ 
# val_data_path: /beat_4english_30_30/val_norm/ 
# test_data_path: /beat_4english_30_30/test_norm/ 
# mean_pose_path: /beat_4english_30_30/train_norm/
# std_pose_path: /beat_4english_30_30/train_norm/


root_path: /data/nas07/PersonalData/danh/PantoMatrix/beat_partial
train_data_path: /beat_4english_30_1_normalized/train_copy/ 
val_data_path: /beat_4english_30_1_normalized/val_copy/ 
test_data_path: /beat_4english_30_1_normalized/test_copy/ 
mean_pose_path: /beat_4english_30_1_normalized/train_copy/
std_pose_path: /beat_4english_30_1_normalized/train_copy/
##-------------------------------------------##


# ##-----------For run in NCHC server-----------##
# root_path: /work/vanthoai97/beat_vicon_hips/data
# train_data_path: /beat_4gnlish_30_30_v0.2.0/train_norm/ 
# val_data_path: /beat_4gnlish_30_30_v0.2.0/val_norm/ 
# test_data_path: /beat_4gnlish_30_30_v0.2.0/test_norm/ 
# mean_pose_path: /beat_4gnlish_30_30_v0.2.0/train_norm/
# std_pose_path: /beat_4gnlish_30_30_v0.2.0/train_norm/
# ##-------------------------------------------##

cache_path: standardize_pose_1/  # nằm trong folder data
stat: ts
dataset: beat_skeleton_final_not_face
# dataset: beat_skeleton_pose_norm

new_cache: True

loader_workers: 8

#-- Need to be changed to work with skeleton
ori_joints: skeleton_joint_full
tar_joints: skeleton_upper
pose_version: skeleton_upper
pose_fps: 30


pose_rep: bvh_rot

##-----Keep unchanged-------##
ddp: False
project: emage_skeleton

##-----Keep unchanged-------##
vae_test_len: 64
vae_test_dim: 84
vae_test_stride: 20
vae_length: 256
vae_codebook_size: 256
vae_layer: 2
vae_grow: [1,1,2,1]
variational: False
##---------------------------##


# pose_dims: 36 # change to work with skeleton
pose_dims: 84 # change to work with skeleton, rotation 6d (14 joints * 6) 

pose_length: 64 #keep unchanged
stride: 20 #keep unchanged


##-----Keep unchanged-------##
word_index_num: 5793
word_dims: 300
batch_size: 32
lr_base: 3e-4
decay_epochs: 780
model: motion_representation
g_name: VQVAEConvZero #VAEConvZero
trainer: aeskeleton_upper_final # change to work with skeleton
##---------------------------##

pretrain: False
# audio_f: 256
# a_pre_encoder: tcn_camn
# a_encoder: lp
# a_fix_pre: False

# freeze_wordembed: False
# word_f: 128
# t_pre_encoder: fasttext
# t_encoder: lp
# t_fix_pre: False

# motion_f: 256
# m_pre_encoder: lp
# m_encoder: lp
# m_fix_pre: False

# facial_f: 128
# f_pre_encoder: lp
# f_encoder: lp
# f_fix_pre: False

#m_decoder: lstm
#decode_fusion: cat
#n_layer: 2
#hidden_size: 512
rec_weight: 1
rec_pos_weight: 1
rec_ver_weight: 1
vel_weight: 1
#vel_weight giống BEAT
# rec_fac_weight: 1
#ita_weight: 0
#iwa_weight: 0
#fusion_mode: sum
# grad_norm: 1
epochs: 800
test_period: 10

## Thêm vào
#disable_filtering: True
multi_length_training: [1] #Vì trong data loader cần biến này#
random_seed: 1234