is_train: True
root_path: /data/nas07/PersonalData/danh/PantoMatrix
out_path: ./outputs/audio2poseglobal/ 
# train_data_path: /beat_4english_30_full/train_copy/ 
# val_data_path: /beat_4english_30_full/val_copy/ 
# test_data_path: /beat_4english_30_full/test_copy/ 
# mean_pose_path: /beat_4english_30_full/train_copy/
# std_pose_path: /beat_4english_30_full/train_copy/

# train_data_path: /beat_4english_30_full/train_clon/ 
# val_data_path: /beat_4english_30_full/val_clon/ 
# test_data_path: /beat_4english_30_full/test_clon/ 
# mean_pose_path: /beat_4english_30_full/train_clon/
# std_pose_path: /beat_4english_30_full/train_clon/

# train_data_path: /beat_4english_30_full7/train_copy/ 
# val_data_path: /beat_4english_30_full7/val_copy/ 
# test_data_path: /beat_4english_30_full7/test_copy/ 
# mean_pose_path: /beat_4english_30_full7/train_copy/
# std_pose_path: /beat_4english_30_full7/train_copy/

# train_data_path: /beat_4english_30_full7_partial/train_copy/ 
# val_data_path: /beat_4english_30_full7_partial/val_copy/ 
# test_data_path: /beat_4english_30_full7_partial/test_copy/ 
# mean_pose_path: /beat_4english_30_full7_partial/train_copy/
# std_pose_path: /beat_4english_30_full7_partial/train_copy/

# train_data_path: /beat_4english_30_full8/train_copy/ 
# val_data_path: /beat_4english_30_full8/val_copy/ 
# test_data_path: /beat_4english_30_full8/test_copy/ 
# mean_pose_path: /beat_4english_30_full8/train_copy/
# std_pose_path: /beat_4english_30_full8/train_copy/

# train_data_path: /beat_4english_30_full9/train_copy/ 
# val_data_path: /beat_4english_30_full9/val_copy/ 
# test_data_path: /beat_4english_30_full9/test_copy/ 
# mean_pose_path: /beat_4english_30_full9/train_copy/
# std_pose_path: /beat_4english_30_full9/train_copy/

train_data_path: /beat_4english_30_mixamo/train_copy/ 
val_data_path: /beat_4english_30_mixamo/val_copy/ 
test_data_path: /beat_4english_30_mixamo/test_copy/ 
mean_pose_path: /beat_4english_30_mixamo/train_copy/
std_pose_path: /beat_4english_30_mixamo/train_copy/

# train_data_path: /beat_4english_30_mixamo3/train_copy/ 
# val_data_path: /beat_4english_30_mixamo3/val_copy/ 
# test_data_path: /beat_4english_30_mixamo3/test_copy/ 
# mean_pose_path: /beat_4english_30_mixamo3/train_copy/
# std_pose_path: /beat_4english_30_mixamo3/train_copy/

stat: wandb
dataset: beat_skeleton_new
new_cache: True
pose_rep: skeleton_cache

# motion config
ori_joints: mixamo_joint_full
tar_joints: mixamo_joint_full
pose_version: mixamo_joint_full #skeleton_handomulti_length_training: [1]
pose_fps: 30


pose_rep: bvh_rot

ddp: False
project: emage_skeleton


# data_path: ./BEAT2/beat_english_v2.0.0/

# e_path:  weights/AESKConv_240_100.bin
eval_model: motion_representation
# e_name: VAESKConv
# test_ckpt: ./EMAGE/emage_240.bin
data_path_1: ./EMAGE/



#-------Keep unchanged-------#
vae_test_len: 32
vae_test_dim: 156
# 276 - 190 + 1 - 12
vae_test_stride: 20
vae_length: 240
vae_codebook_size: 256
vae_layer: 4
vae_grow: [1,1,2,1]
variational: False
#---------------------------#

pose_dims: 156
pose_length: 64
stride: 20

# data config
training_speakers: [2]
# [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30]
# additional_data: False
# cache_path: datasets/beat_cache/beat_smplx_en_emage/

# pose_norm: False

# facial_dims: 51


# rot6d: True
# joint_representation: xyz #???

pre_frames: 4 # not sure for removing

#--------not sure for removing--------#
test_length: 64 
motion_f: 256 
m_pre_encoder: null 
m_encoder: null
m_fix_pre: False
#------------------------------------#
audio_rep: wave16k
facial_rep: facial52
speaker_id: id
word_rep: text
sem_rep: sem
emo_rep: emo
# audio config - removing
# audio_rep: onset+amplitude
# audio_sr: 16000
# audio_fps: 16000
# audio_norm: False
audio_f: 256
# removing--------------#

# a_pre_encoder: tcn_camn
# a_encoder: none
# a_fix_pre: False

#-------removeing--------#
# text config
# word_rep: textgrid 

#------------------------#

word_index_num: 11195
word_dims: 300
freeze_wordembed: False
word_f: 256
t_pre_encoder: fasttext
t_encoder: null
t_fix_pre: False

# facial config
# facial_rep: smplxflame_30
facial_dims: 51
facial_norm: False
facial_f: 0
f_pre_encoder: null
f_encoder: null
f_fix_pre: False

# speaker config
id_rep: onehot
speaker_f: 0

# model config
batch_size: 3
# warmup_epochs: 1
# warmup_lr: 1e-6
lr_base: 5e-4
model: emage_audio
g_name: MAGE_Transformer
trainer: skeleton_emage_noword
hidden_size: 768
n_layer: 1
 
rec_weight: 1
grad_norm: 0.99
epochs: 10
test_period: 1
ll: 3
lf: 3
lu: 3
lh: 3
cl: 1
cf: 0
cu: 1
ch: 1

# new
# train_data_path: /beat_4english_30_full/train_copy/ 
# val_data_path: /beat_4english_30_full/val_copy/ 
# test_data_path: /beat_4english_30_full/test_copy/ 
# mean_pose_path: /beat_4english_30_full/train_copy/
# std_pose_path: /beat_4english_30_full/train_c
# pose_version: skeleton_hand
multi_length_training: [1]

