is_train: True
out_path: ./outputs/inference/ 

test_ckpt: /data/nas07/PersonalData/thoai/beat_vicon_hips/outputs/audio2poseglobal_mixamo/custom/0729_084852_mixamo_emage_noword/last_9.bin
gpus: [0,1]
cache_path: all_pose/

stat: ts
dataset: mixamo_skeleton_emage_final
new_cache: False
loader_workers: 20
batch_size: 80
# loader_workers: 8
# batch_size: 64
# motion config
ori_joints: mixamo_joint_full
tar_joints: mixamo_joint_full
pose_version: mixamo_joint_full
pose_fps: 30

pose_rep: bvh_rot

ddp: False
project: emage_skeleton

eval_model: motion_representation


#-------Keep unchanged-------#
vae_test_len: 32
vae_test_dim: 312 #52*6

vae_test_stride: 20
vae_length: 240
vae_codebook_size: 256
vae_layer: 4
vae_grow: [1,1,2,1]
variational: False
#---------------------------#

pose_dims: 312
pose_length: 64
stride: 20
pre_frames: 4 # not sure for removing

#--------not sure for removing--------#
test_length: 64 
motion_f: 256 
m_pre_encoder: null 
m_encoder: null
m_fix_pre: False
#------------------------------------#
audio_rep: wave16k
facial_rep: facial52
speaker_id: id
audio_f: 256

freeze_wordembed: False
word_f: 256
t_pre_encoder: fasttext
t_encoder: null
t_fix_pre: False

# facial config
# facial_rep: smplxflame_30
facial_dims: 51
facial_norm: False
facial_f: 0
f_pre_encoder: null
f_encoder: null
f_fix_pre: False

# speaker config
id_rep: onehot
speaker_f: 0

# model config
# warmup_epochs: 1
# warmup_lr: 1e-6
lr_base: 5e-4
model: emage_audio
g_name: MAGE_Transformer
trainer: mixamo_emage_beat_final_v2
hidden_size: 768
n_layer: 1
 
rec_weight: 1
grad_norm: 0.99
epochs: 1000
test_period: 10
ll: 3
lf: 3
lu: 3
lh: 3
cl: 1
cf: 0
cu: 1
ch: 1

multi_length_training: [1]


