is_train: True
root_path: /data/nas07/PersonalData/danh/PantoMatrix
out_path: ./outputs/audio2pose_mixamo/ 
# train_data_path: /beat_4english_30_full10/train_copy/ 
# val_data_path: /beat_4english_30_full10/val_copy/ 
# test_data_path: /beat_4english_30_full10/test_copy/ 
# mean_pose_path: /beat_4english_30_full10/train_copy/
# std_pose_path: /beat_4english_30_full10/train_copy/

train_data_path: /beat_4english_30_mixamo/train_copy/ 
val_data_path: /beat_4english_30_mixamo/val_copy/ 
test_data_path: /beat_4english_30_mixamo/test_copy/ 
mean_pose_path: /beat_4english_30_mixamo/train_copy/
std_pose_path: /beat_4english_30_mixamo/train_copy/

# train_data_path: /beat_4english_30_full/train_clon/ 
# val_data_path: /beat_4english_30_full/val_clon/ 
# test_data_path: /beat_4english_30_full/test_clon/ 
# mean_pose_path: /beat_4english_30_full/train_clon/
# std_pose_path: /beat_4english_30_full/train_clon/

# train_data_path: /beat_4english_30_full7/train_copy/ 
# val_data_path: /beat_4english_30_full7/val_copy/ 
# test_data_path: /beat_4english_30_full7/test_copy/ 
# mean_pose_path: /beat_4english_30_full7/train_copy/
# std_pose_path: /beat_4english_30_full7/train_copy/

stat: wandb
dataset: beat_skeleton
new_cache: True

# ori_joints: beat_smplx_joints
# tar_joints: beat_smplx_upper
pose_rep: skeleton_cache
# pose_norm: False


ori_joints: mixamo_joint_full
tar_joints: mixamo_hand
pose_version: mixamo_hand

pose_fps: 30


pose_rep: bvh_rot

##-----Keep unchanged-------##
ddp: False
project: emage_skeleton

##-----Keep unchanged-------##
vae_test_len: 64

vae_test_dim: 96
pose_dims: 96

vae_test_stride: 20
vae_length: 256
vae_codebook_size: 256
vae_layer: 2
vae_grow: [1,1,2,1]
variational: False
##---------------------------##

# pose_dims: 78
pose_dims: 96 # change to work with skeleton

pose_length: 64 #keep unchanged
stride: 20 #keep unchanged

# facial_dims: 100
facial_dims: 51 # change to work with ARKit(52-tongue=51)

##-----Keep unchanged-------##
word_index_num: 11195
word_dims: 300
batch_size: 1
lr_base: 3e-4
decay_epochs: 780
model: motion_representation
g_name: VQVAEConvZero
trainer: aeskeleton_hand # change to work with skeleton
##---------------------------##

# audio_f: 256
# a_pre_encoder: tcn_camn
# a_encoder: lp
# a_fix_pre: False

# freeze_wordembed: False
# word_f: 128
# t_pre_encoder: fasttext
# t_encoder: lp
# t_fix_pre: False

# motion_f: 256
# m_pre_encoder: lp
# m_encoder: lp
# m_fix_pre: False

# facial_f: 128
# f_pre_encoder: lp
# f_encoder: lp
# f_fix_pre: False

#m_decoder: lstm
#decode_fusion: cat
#n_layer: 2
#hidden_size: 512
rec_weight: 1
rec_pos_weight: 1
rec_ver_weight: 1
# rec_fac_weight: 1
#ita_weight: 0
#iwa_weight: 0
#fusion_mode: sum
# grad_norm: 1
epochs: 10
test_period: 2

## Thêm vào
multi_length_training: [1] #Vì trong data loader cần biến này#